name: Build and publish NuGet package to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'

env:
  # Replace the following with your own package name
  PACKAGE_NAME: Anki.Net-mod
  # PACKAGE_VERSION: ${{  $(date +"%Y.%j") }}.${{ github.run_number }}
  PROJECT_PATH: src/Anki.NET
  PROJECT_FILE: src/Anki.NET/Anki.NET.csproj

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: GetDate
      id: t1
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "j"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build
      run: dotnet build -c Release ${{ env.PROJECT_FILE }}

    - name: Create NuGet package
      run: dotnet pack -c Release /p:PackageVersion=${{ steps.t1.outputs.year }}.${{ steps.t1.outputs.week_of_year }}.${{ github.run_number }} ${{ env.PROJECT_FILE }}

    - name: Publish package to GitHub Packages
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
        nuget-version: 'latest'

    - name: Add GitHub Packages as a NuGet source
      run: nuget sources add -name "GitHub Packages" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -Username ${{ github.actor }} -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText

    - name: Push package to GitHub Packages
      run: nuget push -Source "GitHub Packages" -ApiKey ${{ secrets.GITHUB_TOKEN }} ${{ github.workspace }}/${{ env.PROJECT_PATH }}/bin/Release/${{ env.PACKAGE_NAME }}.${{ steps.t1.outputs.year }}.${{ steps.t1.outputs.week_of_year }}.${{ github.run_number }}.nupkg
